import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ar' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations = {
  ar: {
    // Navigation
    dashboard: 'لوحة التحكم',
    pos: 'نقطة البيع',
    inventory: 'المخزون',
    suppliers: 'الموردين',
    clients: 'العملاء',
    documents: 'المستندات',
    waitingList: 'قائمة الانتظار',
    reports: 'التقارير',
    settings: 'الإعدادات',
    
    // Common
    search: 'بحث',
    add: 'إضافة',
    edit: 'تعديل',
    delete: 'حذف',
    save: 'حفظ',
    cancel: 'إلغاء',
    confirm: 'تأكيد',
    name: 'الاسم',
    phone: 'الهاتف',
    address: 'العنوان',
    email: 'البريد الإلكتروني',
    price: 'السعر',
    quantity: 'الكمية',
    total: 'المجموع',
    date: 'التاريخ',
    status: 'الحالة',
    actions: 'الإجراءات',
    
    // POS
    cart: 'السلة',
    checkout: 'الدفع',
    cash: 'نقداً',
    card: 'بطاقة',
    credit: 'آجل',
    partial: 'دفع جزئي',
    
    // Products
    product: 'المنتج',
    products: 'المنتجات',
    buyPrice: 'سعر الشراء',
    sellPrice: 'سعر البيع',
    stock: 'المخزون',
    expiryDate: 'تاريخ الانتهاء',
    lowStock: 'مخزون منخفض',
    
    // Dashboard
    todaySales: 'مبيعات اليوم',
    totalProducts: 'إجمالي المنتجات',
    totalSuppliers: 'إجمالي الموردين',
    totalClients: 'إجمالي العملاء',
    recentSales: 'المبيعات الأخيرة',
    stockAlerts: 'تنبيهات المخزون',
    
    // Company
    companyName: 'متجر مواد البناء والسباكة',
    
    // Workflow
    workflow: 'سير العمل',
    purchaseOrder: 'طلب شراء من المورد',
    goodsReception: 'استلام البضاعة',
    stockIn: 'دخول الى المخزون',
    salesOrder: 'طلب بيع من العميل',
    deliveryNote: 'تسليم البضاعة',
    invoice: 'إصدار الفاتورة',
    
    // Workflow Status
    pending: 'في الانتظار',
    inProgress: 'قيد التنفيذ',
    completed: 'مكتمل',
    cancelled: 'ملغي',
    
    // Document Types
    supplierPurchaseOrder: 'أمر شراء المورد',
    receptionSlip: 'إيصال الاستلام',
    stockEntry: 'إدخال المخزون',
    customerSalesOrder: 'أمر بيع العميل',
    deliverySlip: 'إيصال التسليم',
    invoiceDoc: 'الفاتورة',
    
    // Additional Terms
    traceability: 'إمكانية التتبع',
    documentNumber: 'رقم المستند',
    workflowStatus: 'حالة سير العمل',
    linkedDocuments: 'المستندات المرتبطة',
    createDocument: 'إنشاء مستند',
    viewWorkflow: 'عرض سير العمل',
    trackOrder: 'تتبع الطلب',
    
    // Settings
    generalSettings: 'الإعدادات العامة',
    companyInfo: 'معلومات الشركة',
    userManagement: 'إدارة المستخدمين',
    systemPreferences: 'تفضيلات النظام',
    backupRestore: 'النسخ الاحتياطي والاستعادة',
    notifications: 'الإشعارات',
    security: 'الأمان',
    integrations: 'التكاملات',
    
    // Company Information
    companyAddress: 'عنوان الشركة',
    companyPhone: 'هاتف الشركة',
    companyEmail: 'بريد الشركة الإلكتروني',
    taxNumber: 'الرقم الضريبي',
    commercialRegister: 'السجل التجاري',
    
    // User Management
    users: 'المستخدمون',
    roles: 'الأدوار',
    permissions: 'الصلاحيات',
    addUser: 'إضافة مستخدم',
    editUser: 'تعديل مستخدم',
    deleteUser: 'حذف مستخدم',
    username: 'اسم المستخدم',
    password: 'كلمة المرور',
    role: 'الدور',
    lastLogin: 'آخر تسجيل دخول',
    
    // System Preferences
    language: 'اللغة',
    theme: 'المظهر',
    currency: 'العملة',
    dateFormat: 'تنسيق التاريخ',
    timeZone: 'المنطقة الزمنية',
    
    // Notifications
    emailNotifications: 'إشعارات البريد الإلكتروني',
    smsNotifications: 'إشعارات الرسائل النصية',
    systemAlerts: 'تنبيهات النظام',
    lowStockAlerts: 'تنبيهات المخزون المنخفض',
    expirationAlerts: 'تنبيهات انتهاء الصلاحية',
    
    // Additional missing translations
    category: 'الفئة',
    expiration: 'انتهاء الصلاحية',
    expiringSoon: 'ينتهي قريباً',
    addProduct: 'إضافة منتج',
    noProductsAdded: 'لم يتم إضافة أي منتج. انقر على "إضافة منتج" للبدء.',
    supplierPurchaseOrder: 'أمر شراء المورد',
    receptionSlip: 'إيصال الاستلام',
    stockEntry: 'دخول المخزون',
    customerSalesOrder: 'أمر بيع العميل',
    deliveryNote: 'إيصال التسليم',
    invoiceDoc: 'الفاتورة',
    linkedDocuments: 'المستندات المرتبطة',
    newDocument: 'مستند جديد',
    filters: 'المرشحات',
    manageAllDocuments: 'إدارة جميع المستندات التجارية',
    totalDocuments: 'إجمالي المستندات',
    paid: 'مدفوع',
    pending: 'في الانتظار',
    totalAmount: 'المبلغ الإجمالي',
    searchByNumber: 'البحث بالرقم أو العميل أو المورد...',
    allStatuses: 'جميع الحالات',
    allDocuments: 'جميع المستندات',
    type: 'النوع',
    number: 'الرقم',
    step: 'الخطوة',
    clientSupplier: 'العميل/المورد',
    amount: 'المبلغ',
    linked: 'مرتبط',
    viewDocument: 'عرض المستند',
    downloadPDF: 'تحميل PDF',
    editDocument: 'تعديل المستند',
    deleteDocument: 'حذف المستند',
    noDocumentsFound: 'لم يتم العثور على مستندات',
    loadingDocuments: 'جاري تحميل المستندات...',
    errorLoadingDocuments: 'خطأ في تحميل المستندات',
    retry: 'إعادة المحاولة',
    
    // Waiting List
    waitingList: 'قائمة الانتظار',
    waitingListProducts: 'منتجات قائمة الانتظار',
    addToWaitingList: 'إضافة إلى قائمة الانتظار',
    addToInventory: 'إضافة إلى المخزون',
    removeFromWaitingList: 'إزالة من قائمة الانتظار',
    clearWaitingList: 'مسح قائمة الانتظار',
    noProductsInWaitingList: 'لا توجد منتجات في قائمة الانتظار في الوقت الحالي',
    normalQuantity: 'الكمية العادية',
    missingQuantity: 'الكمية المفقودة',
    surplusQuantity: 'الكمية الفائضة',
    addWithMissingQuantity: 'إضافة مع كمية مفقودة',
    addWithSurplusQuantity: 'إضافة مع كمية فائضة',
    addNormalQuantity: 'إضافة الكمية العادية',
    missingQuantityField: 'حقل الكمية المفقودة',
    surplusQuantityField: 'حقل الكمية الفائضة',
    incorrectQuantities: 'كميات غير صحيحة',
    quantityManquante: 'كمية مفقودة',
    quantitySurplus: 'كمية فائضة',
    cannotAddToInventoryMissing: 'لا يمكن إضافة هذا المنتج إلى المخزون لأنه يحتوي على كمية مفقودة. يرجى حل مشكلة الكمية المفقودة أولاً.',
    cannotAddToInventorySurplus: 'لا يمكن إضافة هذا المنتج إلى المخزون لأنه يحتوي على كمية فائضة. يرجى حل مشكلة الكمية الفائضة أولاً.',
    confirmAddNormalQuantity: 'هذا المنتج يحتوي على كمية فائضة من {surplusQuantity}. هل تريد إضافة الكمية العادية ({normalQuantity}) فقط إلى المخزون؟ ستظل الكمية الفائضة في قائمة الانتظار.',
    normalQuantityAddedToInventory: 'تم إضافة الكمية العادية إلى المخزون. تم الاحتفاظ بالكمية الفائضة في قائمة الانتظار.',
    productAddedToInventory: 'تم إضافة المنتج إلى المخزون وإزالته من قائمة الانتظار',
    productAddedWithMissingQuantity: 'تم إضافة المنتج مع كمية مفقودة إلى قائمة الانتظار',
    productAddedWithSurplusQuantity: 'تم إضافة المنتج مع كمية فائضة إلى قائمة الانتظار',
    productAlreadyInWaitingList: 'المنتج موجود بالفعل في قائمة الانتظار',
    productUpdatedInWaitingList: 'تم تحديث المنتج في قائمة الانتظار، تم تحديث العلم (مفقود)',
    productUpdatedInWaitingListSurplus: 'تم تحديث المنتج في قائمة الانتظار، تم تحديث العلم (فائض)',
    missingQuantityAddedToWaitingList: 'تم إضافة الكمية المفقودة إلى قائمة الانتظار',
    surplusQuantityAddedToWaitingList: 'تم إضافة الكمية الفائضة إلى قائمة الانتظار',
    missing: 'مفقود',
    surplus: 'فائض',
    normal: 'عادي',
    
    // Inventory specific
    addNewProduct: 'إضافة منتج جديد',
    editProduct: 'تعديل المنتج',
    deleteProduct: 'حذف المنتج',
    productName: 'اسم المنتج',
    productCode: 'كود المنتج',
    productDescription: 'وصف المنتج',
    productCategory: 'فئة المنتج',
    productSize: 'حجم المنتج',
    productLocation: 'موقع المنتج',
    productImage: 'صورة المنتج',
    currentStock: 'المخزون الحالي',
    minimumStock: 'الحد الأدنى للمخزون',
    arrivalDate: 'تاريخ الوصول',
    totalPurchases: 'إجمالي المشتريات',
    totalReturns: 'إجمالي المرتجعات',
    isActive: 'نشط',
    createdAt: 'تاريخ الإنشاء',
    updatedAt: 'تاريخ التحديث',
    uploadImage: 'رفع صورة',
    imagePreview: 'معاينة الصورة',
    selectImage: 'اختر صورة',
    noImageSelected: 'لم يتم اختيار صورة',
    confirmDeleteProduct: 'هل أنت متأكد من أنك تريد حذف هذا المنتج؟',
    errorCreatingProduct: 'خطأ في إنشاء المنتج',
    errorUpdatingProduct: 'خطأ في تحديث المنتج',
    errorDeletingProduct: 'خطأ في حذف المنتج',
    productCreatedSuccessfully: 'تم إنشاء المنتج بنجاح',
    productUpdatedSuccessfully: 'تم تحديث المنتج بنجاح',
    productDeletedSuccessfully: 'تم حذف المنتج بنجاح',
    
    // Suppliers specific
    addNewSupplier: 'إضافة مورد جديد',
    editSupplier: 'تعديل المورد',
    deleteSupplier: 'حذف المورد',
    supplierName: 'اسم المورد',
    supplierCode: 'كود المورد',
    supplierContact: 'جهة الاتصال',
    supplierPhone: 'هاتف المورد',
    supplierEmail: 'بريد المورد الإلكتروني',
    supplierAddress: 'عنوان المورد',
    supplierCity: 'مدينة المورد',
    supplierCountry: 'دولة المورد',
    supplierNotes: 'ملاحظات المورد',
    isActiveSupplier: 'مورد نشط',
    supplierCreatedAt: 'تاريخ إنشاء المورد',
    supplierUpdatedAt: 'تاريخ تحديث المورد',
    confirmDeleteSupplier: 'هل أنت متأكد من أنك تريد حذف هذا المورد؟',
    errorCreatingSupplier: 'خطأ في إنشاء المورد',
    errorUpdatingSupplier: 'خطأ في تحديث المورد',
    errorDeletingSupplier: 'خطأ في حذف المورد',
    supplierCreatedSuccessfully: 'تم إنشاء المورد بنجاح',
    supplierUpdatedSuccessfully: 'تم تحديث المورد بنجاح',
    supplierDeletedSuccessfully: 'تم حذف المورد بنجاح',
    newOrder: 'طلب جديد',
    addOrderItem: 'إضافة عنصر طلب',
    addNewProductItem: 'إضافة عنصر منتج جديد',
    orderItems: 'عناصر الطلب',
    orderTotal: 'إجمالي الطلب',
    unitPrice: 'سعر الوحدة',
    orderQuantity: 'كمية الطلب',
    orderUnit: 'وحدة الطلب',
    orderNotes: 'ملاحظات الطلب',
    createOrder: 'إنشاء طلب',
    updateOrder: 'تحديث الطلب',
    cancelOrder: 'إلغاء الطلب',
    orderCreatedSuccessfully: 'تم إنشاء الطلب بنجاح',
    orderUpdatedSuccessfully: 'تم تحديث الطلب بنجاح',
    orderDeletedSuccessfully: 'تم حذف الطلب بنجاح',
    
    // Clients specific
    addNewClient: 'إضافة عميل جديد',
    editClient: 'تعديل العميل',
    deleteClient: 'حذف العميل',
    clientName: 'اسم العميل',
    clientCode: 'كود العميل',
    clientContact: 'جهة الاتصال',
    clientPhone: 'هاتف العميل',
    clientEmail: 'بريد العميل الإلكتروني',
    clientAddress: 'عنوان العميل',
    clientCity: 'مدينة العميل',
    clientCountry: 'دولة العميل',
    clientNotes: 'ملاحظات العميل',
    isActiveClient: 'عميل نشط',
    clientCreatedAt: 'تاريخ إنشاء العميل',
    clientUpdatedAt: 'تاريخ تحديث العميل',
    confirmDeleteClient: 'هل أنت متأكد من أنك تريد حذف هذا العميل؟',
    errorCreatingClient: 'خطأ في إنشاء العميل',
    errorUpdatingClient: 'خطأ في تحديث العميل',
    errorDeletingClient: 'خطأ في حذف العميل',
    clientCreatedSuccessfully: 'تم إنشاء العميل بنجاح',
    clientUpdatedSuccessfully: 'تم تحديث العميل بنجاح',
    clientDeletedSuccessfully: 'تم حذف العميل بنجاح',
    newSale: 'بيع جديد',
    addSaleItem: 'إضافة عنصر بيع',
    saleItems: 'عناصر البيع',
    saleTotal: 'إجمالي البيع',
    saleQuantity: 'كمية البيع',
    saleUnit: 'وحدة البيع',
    saleNotes: 'ملاحظات البيع',
    createSale: 'إنشاء بيع',
    updateSale: 'تحديث البيع',
    cancelSale: 'إلغاء البيع',
    saleCreatedSuccessfully: 'تم إنشاء البيع بنجاح',
    saleUpdatedSuccessfully: 'تم تحديث البيع بنجاح',
    saleDeletedSuccessfully: 'تم حذف البيع بنجاح',
    
    // Documents specific
    documentType: 'نوع المستند',
    documentNumber: 'رقم المستند',
    documentDate: 'تاريخ المستند',
    documentStatus: 'حالة المستند',
    documentNotes: 'ملاحظات المستند',
    documentAmount: 'مبلغ المستند',
    documentClient: 'عميل المستند',
    documentSupplier: 'مورد المستند',
    documentItems: 'عناصر المستند',
    documentTotal: 'إجمالي المستند',
    documentSubtotal: 'المجموع الفرعي للمستند',
    documentTax: 'ضريبة المستند',
    documentTaxRate: 'معدل الضريبة',
    documentDiscount: 'خصم المستند',
    documentDiscountRate: 'معدل الخصم',
    documentShipping: 'شحن المستند',
    documentPaymentMethod: 'طريقة الدفع',
    documentPaymentStatus: 'حالة الدفع',
    documentDueDate: 'تاريخ الاستحقاق',
    documentReference: 'مرجع المستند',
    documentWorkflowStep: 'خطوة سير العمل',
    documentLinkedDocuments: 'المستندات المرتبطة',
    documentCreatedAt: 'تاريخ إنشاء المستند',
    documentUpdatedAt: 'تاريخ تحديث المستند',
    createNewDocument: 'إنشاء مستند جديد',
    downloadDocument: 'تحميل المستند',
    printDocument: 'طباعة المستند',
    emailDocument: 'إرسال المستند بالبريد',
    duplicateDocument: 'نسخ المستند',
    archiveDocument: 'أرشفة المستند',
    restoreDocument: 'استعادة المستند',
    confirmDeleteDocument: 'هل أنت متأكد من أنك تريد حذف هذا المستند؟',
    errorCreatingDocument: 'خطأ في إنشاء المستند',
    errorUpdatingDocument: 'خطأ في تحديث المستند',
    errorDeletingDocument: 'خطأ في حذف المستند',
    documentCreatedSuccessfully: 'تم إنشاء المستند بنجاح',
    documentUpdatedSuccessfully: 'تم تحديث المستند بنجاح',
    documentDeletedSuccessfully: 'تم حذف المستند بنجاح',
    documentArchivedSuccessfully: 'تم أرشفة المستند بنجاح',
    documentRestoredSuccessfully: 'تم استعادة المستند بنجاح',
    
    // Form fields
    required: 'مطلوب',
    optional: 'اختياري',
    selectOption: 'اختر خيار',
    enterValue: 'أدخل قيمة',
    enterText: 'أدخل نص',
    enterNumber: 'أدخل رقم',
    enterEmail: 'أدخل البريد الإلكتروني',
    enterPhone: 'أدخل رقم الهاتف',
    enterDate: 'أدخل التاريخ',
    selectDate: 'اختر التاريخ',
    selectTime: 'اختر الوقت',
    selectFile: 'اختر ملف',
    browseFiles: 'تصفح الملفات',
    dragDropFiles: 'اسحب وأفلت الملفات هنا',
    maxFileSize: 'الحد الأقصى لحجم الملف',
    allowedFileTypes: 'أنواع الملفات المسموحة',
    fileUploaded: 'تم رفع الملف',
    fileUploadError: 'خطأ في رفع الملف',
    fileTooLarge: 'الملف كبير جداً',
    invalidFileType: 'نوع ملف غير صالح',
    
    // Validation messages
    fieldRequired: 'هذا الحقل مطلوب',
    fieldTooShort: 'هذا الحقل قصير جداً',
    fieldTooLong: 'هذا الحقل طويل جداً',
    invalidEmail: 'البريد الإلكتروني غير صالح',
    invalidPhone: 'رقم الهاتف غير صالح',
    invalidNumber: 'الرقم غير صالح',
    invalidDate: 'التاريخ غير صالح',
    invalidUrl: 'الرابط غير صالح',
    passwordTooShort: 'كلمة المرور قصيرة جداً',
    passwordMismatch: 'كلمات المرور غير متطابقة',
    usernameExists: 'اسم المستخدم موجود بالفعل',
    emailExists: 'البريد الإلكتروني موجود بالفعل',
    
    // Success messages
    operationSuccessful: 'تمت العملية بنجاح',
    dataSaved: 'تم حفظ البيانات',
    dataUpdated: 'تم تحديث البيانات',
    dataDeleted: 'تم حذف البيانات',
    dataRestored: 'تم استعادة البيانات',
    dataArchived: 'تم أرشفة البيانات',
    dataExported: 'تم تصدير البيانات',
    dataImported: 'تم استيراد البيانات',
    
    // Error messages
    operationFailed: 'فشلت العملية',
    dataNotSaved: 'لم يتم حفظ البيانات',
    dataNotUpdated: 'لم يتم تحديث البيانات',
    dataNotDeleted: 'لم يتم حذف البيانات',
    dataNotRestored: 'لم يتم استعادة البيانات',
    dataNotArchived: 'لم يتم أرشفة البيانات',
    dataNotExported: 'لم يتم تصدير البيانات',
    dataNotImported: 'لم يتم استيراد البيانات',
    networkError: 'خطأ في الشبكة',
    serverError: 'خطأ في الخادم',
    unauthorized: 'غير مصرح',
    forbidden: 'محظور',
    notFound: 'غير موجود',
    conflict: 'تعارض',
    timeout: 'انتهت المهلة الزمنية',
    
    // Additional missing translations
    code: 'الكود',
    stateQuantity: 'حالة الكمية',
    viewDocument: 'عرض المستند',
    modifyDocument: 'تعديل المستند',
    spectateDocument: 'مراقبة المستند',
    documentDetails: 'تفاصيل المستند',
    documentInformation: 'معلومات المستند',
    documentItems: 'عناصر المستند',
    documentTotal: 'إجمالي المستند',
    documentSubtotal: 'المجموع الفرعي',
    documentTax: 'الضريبة',
    documentDiscount: 'الخصم',
    documentShipping: 'الشحن',
    documentPayment: 'الدفع',
    documentNotes: 'ملاحظات المستند',
    documentStatus: 'حالة المستند',
    documentType: 'نوع المستند',
    documentNumber: 'رقم المستند',
    documentDate: 'تاريخ المستند',
    documentAmount: 'مبلغ المستند',
    documentClient: 'العميل',
    documentSupplier: 'المورد',
    documentWorkflow: 'سير العمل',
    documentLinked: 'مرتبط',
    documentActions: 'إجراءات المستند',
    documentEdit: 'تعديل المستند',
    documentDelete: 'حذف المستند',
    documentDownload: 'تحميل المستند',
    documentPrint: 'طباعة المستند',
    documentEmail: 'إرسال المستند',
    documentDuplicate: 'نسخ المستند',
    documentArchive: 'أرشفة المستند',
    documentRestore: 'استعادة المستند',
    documentClose: 'إغلاق المستند',
    documentSave: 'حفظ المستند',
    documentCancel: 'إلغاء المستند',
    documentConfirm: 'تأكيد المستند',
    documentBack: 'رجوع للمستند',
    documentNext: 'التالي للمستند',
    documentPrevious: 'السابق للمستند',
    documentFirst: 'الأول للمستند',
    documentLast: 'الأخير للمستند',
    documentAll: 'جميع المستندات',
    documentNone: 'لا توجد مستندات',
    documentSome: 'بعض المستندات',
    documentMany: 'كثير من المستندات',
    documentFew: 'قليل من المستندات',
    documentOther: 'مستندات أخرى',
    documentAnother: 'مستند آخر',
    documentSame: 'نفس المستند',
    documentDifferent: 'مستند مختلف',
    documentSimilar: 'مستند مشابه',
    documentIdentical: 'مستند مطابق',
    documentUnique: 'مستند فريد',
    documentCommon: 'مستند شائع',
    documentRare: 'مستند نادر',
    documentFrequent: 'مستند متكرر',
    documentOccasional: 'مستند عرضي',
    documentRegular: 'مستند منتظم',
    documentIrregular: 'مستند غير منتظم',
    documentConstant: 'مستند ثابت',
    documentVariable: 'مستند متغير',
    documentFixed: 'مستند ثابت',
    documentFlexible: 'مستند مرن',
    documentRigid: 'مستند صلب',
    documentSoft: 'مستند ناعم',
    documentHard: 'مستند قاس',
    documentEasy: 'مستند سهل',
    documentDifficult: 'مستند صعب',
    documentSimple: 'مستند بسيط',
    documentComplex: 'مستند معقد',
    documentBasic: 'مستند أساسي',
    documentAdvanced: 'مستند متقدم',
    documentBeginner: 'مستند مبتدئ',
    documentExpert: 'مستند خبير',
    documentProfessional: 'مستند محترف',
    documentAmateur: 'مستند هاوي',
    documentSkilled: 'مستند ماهر',
    documentUnskilled: 'مستند غير ماهر',
    documentTrained: 'مستند مدرب',
    documentUntrained: 'مستند غير مدرب',
    documentQualified: 'مستند مؤهل',
    documentUnqualified: 'مستند غير مؤهل',
    documentCertified: 'مستند معتمد',
    documentUncertified: 'مستند غير معتمد',
    documentLicensed: 'مستند مرخص',
    documentUnlicensed: 'مستند غير مرخص',
    documentAuthorized: 'مستند مصرح',
    documentUnauthorized: 'مستند غير مصرح',
    documentPermitted: 'مستند مسموح',
    documentProhibited: 'مستند محظور',
    documentAllowed: 'مستند مسموح',
    documentForbidden: 'مستند محظور',
    documentLegal: 'مستند قانوني',
    documentIllegal: 'مستند غير قانوني',
    documentValid: 'مستند صالح',
    documentInvalid: 'مستند غير صالح',
    documentCorrect: 'مستند صحيح',
    documentIncorrect: 'مستند غير صحيح',
    documentRight: 'مستند صحيح',
    documentWrong: 'مستند خطأ',
    documentTrue: 'مستند صحيح',
    documentFalse: 'مستند خطأ',
    documentYes: 'مستند نعم',
    documentNo: 'مستند لا',
    documentOk: 'مستند موافق',
    documentCancel: 'مستند إلغاء',
    documentConfirm: 'مستند تأكيد',
    documentDeny: 'مستند رفض',
    documentAllow: 'مستند السماح',
    documentBlock: 'مستند حظر',
    documentUnblock: 'مستند إلغاء الحظر',
    documentLock: 'مستند قفل',
    documentUnlock: 'مستند فتح',
    documentSecure: 'مستند آمن',
    documentInsecure: 'مستند غير آمن',
    documentSafe: 'مستند آمن',
    documentUnsafe: 'مستند غير آمن',
    documentProtected: 'مستند محمي',
    documentUnprotected: 'مستند غير محمي',
    documentPrivate: 'مستند خاص',
    documentPublic: 'مستند عام',
    documentInternal: 'مستند داخلي',
    documentExternal: 'مستند خارجي',
    documentLocal: 'مستند محلي',
    documentRemote: 'مستند بعيد',
    documentOnline: 'مستند متصل',
    documentOffline: 'مستند غير متصل',
    documentAvailable: 'مستند متاح',
    documentUnavailable: 'مستند غير متاح',
    documentAccessible: 'مستند يمكن الوصول إليه',
    documentInaccessible: 'مستند لا يمكن الوصول إليه',
    documentVisible: 'مستند مرئي',
    documentInvisible: 'مستند غير مرئي',
    documentHidden: 'مستند مخفي',
    documentShown: 'مستند مُظهر',
    documentDisplayed: 'مستند معروض',
    documentOpen: 'مستند مفتوح',
    documentClosed: 'مستند مغلق',
    documentActive: 'مستند نشط',
    documentInactive: 'مستند غير نشط',
    documentEnabled: 'مستند مفعل',
    documentDisabled: 'مستند معطل',
    documentOn: 'مستند تشغيل',
    documentOff: 'مستند إيقاف',
    documentUp: 'مستند أعلى',
    documentDown: 'مستند أسفل',
    documentLeft: 'مستند يسار',
    documentRight: 'مستند يمين',
    documentTop: 'مستند أعلى',
    documentBottom: 'مستند أسفل',
    documentFront: 'مستند أمام',
    documentBack: 'مستند خلف',
    documentInside: 'مستند داخل',
    documentOutside: 'مستند خارج',
    documentHere: 'مستند هنا',
    documentThere: 'مستند هناك',
    documentEverywhere: 'مستند في كل مكان',
    documentNowhere: 'مستند في أي مكان',
    documentSomewhere: 'مستند في مكان ما',
    documentAnywhere: 'مستند في أي مكان',
    documentHome: 'مستند المنزل',
    documentWork: 'مستند العمل',
    documentSchool: 'مستند المدرسة',
    documentOffice: 'مستند المكتب',
    documentStore: 'مستند المتجر',
    documentShop: 'مستند المحل',
    documentMarket: 'مستند السوق',
    documentMall: 'مستند المول',
    documentCenter: 'مستند المركز',
    documentPlace: 'مستند المكان',
    documentLocation: 'مستند الموقع',
    documentPosition: 'مستند الموضع',
    documentSpot: 'مستند النقطة',
    documentPoint: 'مستند النقطة',
    documentArea: 'مستند المنطقة',
    documentZone: 'مستند المنطقة',
    documentRegion: 'مستند المنطقة',
    documentCountry: 'مستند البلد',
    documentCity: 'مستند المدينة',
    documentTown: 'مستند البلدة',
    documentVillage: 'مستند القرية',
    documentStreet: 'مستند الشارع',
    documentRoad: 'مستند الطريق',
    documentAvenue: 'مستند الشارع',
    documentBoulevard: 'مستند الشارع',
    documentLane: 'مستند الممر',
    documentPath: 'مستند المسار',
    documentWay: 'مستند الطريق',
    documentRoute: 'مستند المسار',
    documentDirection: 'مستند الاتجاه',
    documentDistance: 'مستند المسافة',
    documentLength: 'مستند الطول',
    documentWidth: 'مستند العرض',
    documentHeight: 'مستند الارتفاع',
    documentDepth: 'مستند العمق',
    documentSize: 'مستند الحجم',
    documentWeight: 'مستند الوزن',
    documentMass: 'مستند الكتلة',
    documentVolume: 'مستند الحجم',
    documentCapacity: 'مستند السعة',
    documentSpeed: 'مستند السرعة',
    documentVelocity: 'مستند السرعة',
    documentAcceleration: 'مستند التسارع',
    documentForce: 'مستند القوة',
    documentPressure: 'مستند الضغط',
    documentTemperature: 'مستند درجة الحرارة',
    documentHeat: 'مستند الحرارة',
    documentCold: 'مستند البرودة',
    documentWarm: 'مستند دافئ',
    documentCool: 'مستند بارد',
    documentHot: 'مستند ساخن',
    documentFreezing: 'مستند متجمد',
    documentBoiling: 'مستند غليان',
    documentMelting: 'مستند ذوبان',
    documentSolid: 'مستند صلب',
    documentLiquid: 'مستند سائل',
    documentGas: 'مستند غاز',
    documentPlasma: 'مستند بلازما',
    documentMatter: 'مستند المادة',
    documentEnergy: 'مستند الطاقة',
    documentPower: 'مستند القوة',
    documentStrength: 'مستند القوة',
    documentWeakness: 'مستند الضعف',
    documentStrong: 'مستند قوي',
    documentWeak: 'مستند ضعيف',
    documentHard: 'مستند قاس',
    documentSoft: 'مستند ناعم',
    documentSmooth: 'مستند ناعم',
    documentRough: 'مستند خشن',
    documentSharp: 'مستند حاد',
    documentDull: 'مستند بليد',
    documentBright: 'مستند مشرق',
    documentDark: 'مستند مظلم',
    documentLight: 'مستند فاتح',
    documentHeavy: 'مستند ثقيل',
    documentLight: 'مستند خفيف',
    documentBig: 'مستند كبير',
    documentSmall: 'مستند صغير',
    documentLarge: 'مستند كبير',
    documentTiny: 'مستند صغير جداً',
    documentHuge: 'مستند ضخم',
    documentEnormous: 'مستند هائل',
    documentGiant: 'مستند عملاق',
    documentMiniature: 'مستند مصغر',
    documentMicro: 'مستند دقيق',
    documentMacro: 'مستند كبير',
    documentMega: 'مستند كبير جداً',
    documentGiga: 'مستند كبير جداً',
    documentTera: 'مستند كبير جداً',
    documentPeta: 'مستند كبير جداً',
    documentExa: 'مستند كبير جداً',
    documentZetta: 'مستند كبير جداً',
    documentYotta: 'مستند كبير جداً',
    documentKilo: 'مستند كيلو',
    documentHecto: 'مستند هكتو',
    documentDeca: 'مستند ديكا',
    documentDeci: 'مستند ديسي',
    documentCenti: 'مستند ستي',
    documentMilli: 'مستند ملي',
    documentMicro: 'مستند ميكرو',
    documentNano: 'مستند نانو',
    documentPico: 'مستند بيكو',
    documentFemto: 'مستند فيمتو',
    documentAtto: 'مستند أتو',
    documentZepto: 'مستند زبتو',
    documentYocto: 'مستند يوكتو',
    
    // Missing translations
    code: 'الكود',
    stateQuantity: 'حالة الكمية',
    modifyDocument: 'تعديل المستند',
    spectateDocument: 'مراقبة المستند',
    close: 'إغلاق',
    
    // Document form fields
    documentType: 'نوع المستند',
    notModifiable: 'غير قابل للتعديل',
    selectType: 'اختر النوع',
    status: 'الحالة',
    documentStatus: 'حالة المستند',
    draft: 'مسودة',
    sent: 'مرسل',
    paid: 'مدفوع',
    cancelled: 'ملغي',
    totalAmount: 'المبلغ الإجمالي',
    client: 'العميل',
    selectClient: 'اختر العميل',
    supplier: 'المورد',
    selectSupplier: 'اختر المورد',
    
    // Reports page
    lowStockProducts: 'المنتجات منخفضة المخزون',
    stock: 'المخزون',
    lowStock: 'مخزون منخفض',
    min: 'الحد الأدنى',
    allStocksCorrect: 'جميع المخزونات صحيحة',
    clientsWithHighCredit: 'العملاء ذوو الائتمان المرتفع',
    purchases: 'المشتريات',
    credit: 'الائتمان',
    noClientsWithHighCredit: 'لا يوجد عملاء بائتمان مرتفع',
    monthlyEvolution: 'التطور الشهري',
    
    // Document modification specific fields
    automaticDocument: 'مستند تلقائي',
    documentGeneratedByWorkflow: 'تم إنشاء هذا المستند تلقائياً بواسطة سير العمل.',
    supplierOrderDetails: 'تفاصيل طلب المورد',
    desiredDeliveryDate: 'تاريخ التسليم المطلوب',
    orderedProducts: 'المنتجات المطلوبة',
    nameCode: 'الاسم/الكود',
    select: 'اختر',
    addToWaitingList: 'إضافة إلى قائمة الانتظار',
    addWithMissingQuantity: 'إضافة مع الكمية المفقودة',
    addWithSurplusQuantity: 'إضافة مع الكمية الفائضة',
    
    // Waiting List page translations
    waitingListTitle: 'قائمة انتظار المنتجات',
    total: 'المجموع',
    clear: 'مسح',
    noProductsInWaitingList: 'لا توجد منتجات في قائمة الانتظار في الوقت الحالي.',
    name: 'الاسم',
    category: 'الفئة',
    missingQuantity: 'الكمية المفقودة',
    surplusQuantity: 'الكمية الفائضة',
    unit: 'الوحدة',
    unitPrice: 'سعر الوحدة',
    totalPrice: 'المجموع',
    quantity: 'الكمية',
    actions: 'الإجراءات',
    normal: 'عادي',
    missing: 'مفقود',
    surplus: 'فائض',
    addToInventory: 'إضافة إلى المخزون',
    addNormalQuantity: 'إضافة الكمية العادية',
    remove: 'حذف',
    cannotAddToInventoryMissing: 'لا يمكن إضافة هذا المنتج إلى المخزون لأنه يحتوي على كمية مفقودة. يرجى حل مشكلة الكمية المفقودة أولاً.',
    confirmAddNormalQuantity: 'هذا المنتج يحتوي على كمية فائضة من {surplusQuantity}. هل تريد إضافة الكمية العادية فقط ({quantity}) إلى المخزون؟ ستظل الكمية الفائضة في قائمة الانتظار.',
    confirmClearWaitingList: 'هل تريد مسح قائمة الانتظار بالكامل؟',
    
    // Document modification/viewing fields
    documentNumber: 'الرقم',
    documentDate: 'التاريخ',
    documentClient: 'العميل',
    documentSupplier: 'المورد',
    documentItems: 'العناصر',
    documentTotal: 'المجموع',
    documentSubtotal: 'المجموع الفرعي',
    documentTax: 'الضريبة',
    documentDiscount: 'الخصم',
    documentShipping: 'الشحن',
    documentPayment: 'الدفع',
    documentNotes: 'الملاحظات',
    documentStatus: 'الحالة',
    documentType: 'النوع',
    documentAmount: 'المبلغ',
    documentWorkflow: 'سير العمل',
    documentLinked: 'مرتبط',
    documentActions: 'الإجراءات',
    documentEdit: 'تعديل',
    documentDelete: 'حذف',
    documentDownload: 'تحميل',
    documentPrint: 'طباعة',
    documentEmail: 'إرسال',
    documentDuplicate: 'نسخ',
    documentArchive: 'أرشفة',
    documentRestore: 'استعادة',
    documentClose: 'إغلاق',
    documentSave: 'حفظ',
    documentCancel: 'إلغاء',
    documentConfirm: 'تأكيد',
    documentBack: 'رجوع',
    documentNext: 'التالي',
    documentPrevious: 'السابق',
    documentFirst: 'الأول',
    documentLast: 'الأخير',
    documentAll: 'الكل',
    documentNone: 'لا شيء',
    documentSome: 'بعض',
    documentMany: 'كثير',
    documentFew: 'قليل',
    documentOther: 'أخرى',
    documentAnother: 'آخر',
    documentSame: 'نفس',
    documentDifferent: 'مختلف',
    documentSimilar: 'مشابه',
    documentIdentical: 'مطابق',
    documentUnique: 'فريد',
    documentCommon: 'شائع',
    documentRare: 'نادر',
    documentFrequent: 'متكرر',
    documentOccasional: 'عرضي',
    documentRegular: 'منتظم',
    documentIrregular: 'غير منتظم',
    documentConstant: 'ثابت',
    documentVariable: 'متغير',
    documentFixed: 'ثابت',
    documentFlexible: 'مرن',
    documentRigid: 'صلب',
    documentSoft: 'ناعم',
    documentHard: 'قاس',
    documentEasy: 'سهل',
    documentDifficult: 'صعب',
    documentSimple: 'بسيط',
    documentComplex: 'معقد',
    documentBasic: 'أساسي',
    documentAdvanced: 'متقدم',
    documentBeginner: 'مبتدئ',
    documentExpert: 'خبير',
    documentProfessional: 'محترف',
    documentAmateur: 'هاوي',
    documentSkilled: 'ماهر',
    documentUnskilled: 'غير ماهر',
    documentTrained: 'مدرب',
    documentUntrained: 'غير مدرب',
    documentQualified: 'مؤهل',
    documentUnqualified: 'غير مؤهل',
    documentCertified: 'معتمد',
    documentUncertified: 'غير معتمد',
    documentLicensed: 'مرخص',
    documentUnlicensed: 'غير مرخص',
    documentAuthorized: 'مصرح',
    documentUnauthorized: 'غير مصرح',
    documentPermitted: 'مسموح',
    documentProhibited: 'محظور',
    documentAllowed: 'مسموح',
    documentForbidden: 'محظور',
    documentLegal: 'قانوني',
    documentIllegal: 'غير قانوني',
    documentValid: 'صالح',
    documentInvalid: 'غير صالح',
    documentCorrect: 'صحيح',
    documentIncorrect: 'غير صحيح',
    documentRight: 'صحيح',
    documentWrong: 'خطأ',
    documentTrue: 'صحيح',
    documentFalse: 'خطأ',
    documentYes: 'نعم',
    documentNo: 'لا',
    documentOk: 'موافق',
    documentCancel: 'إلغاء',
    documentConfirm: 'تأكيد',
    documentDeny: 'رفض',
    documentAllow: 'السماح',
    documentBlock: 'حظر',
    documentUnblock: 'إلغاء الحظر',
    documentLock: 'قفل',
    documentUnlock: 'فتح',
    documentSecure: 'آمن',
    documentInsecure: 'غير آمن',
    documentSafe: 'آمن',
    documentUnsafe: 'خطر',
    documentProtected: 'محمي',
    documentUnprotected: 'غير محمي',
    documentPrivate: 'خاص',
    documentPublic: 'عام',
    documentInternal: 'داخلي',
    documentExternal: 'خارجي',
    documentLocal: 'محلي',
    documentRemote: 'بعيد',
    documentOnline: 'متصل',
    documentOffline: 'غير متصل',
    documentAvailable: 'متاح',
    documentUnavailable: 'غير متاح',
    documentAccessible: 'يمكن الوصول إليه',
    documentInaccessible: 'لا يمكن الوصول إليه',
    documentVisible: 'مرئي',
    documentInvisible: 'غير مرئي',
    documentHidden: 'مخفي',
    documentShown: 'مُظهر',
    documentDisplayed: 'معروض',
    documentOpen: 'مفتوح',
    documentClosed: 'مغلق',
    documentActive: 'نشط',
    documentInactive: 'غير نشط',
    documentEnabled: 'مفعل',
    documentDisabled: 'معطل',
    documentOn: 'تشغيل',
    documentOff: 'إيقاف',
    documentUp: 'أعلى',
    documentDown: 'أسفل',
    documentLeft: 'يسار',
    documentRight: 'يمين',
    documentTop: 'أعلى',
    documentBottom: 'أسفل',
    documentFront: 'أمام',
    documentBack: 'خلف',
    documentInside: 'داخل',
    documentOutside: 'خارج',
    documentHere: 'هنا',
    documentThere: 'هناك',
    documentEverywhere: 'في كل مكان',
    documentNowhere: 'في أي مكان',
    documentSomewhere: 'في مكان ما',
    documentAnywhere: 'في أي مكان',
    documentHome: 'المنزل',
    documentWork: 'العمل',
    documentSchool: 'المدرسة',
    documentOffice: 'المكتب',
    documentStore: 'المتجر',
    documentShop: 'المحل',
    documentMarket: 'السوق',
    documentMall: 'المركز التجاري',
    documentCenter: 'المركز',
    documentPlace: 'المكان',
    documentLocation: 'الموقع',
    documentPosition: 'الموضع',
    documentSpot: 'النقطة',
    documentPoint: 'النقطة',
    documentArea: 'المنطقة',
    documentZone: 'المنطقة',
    documentRegion: 'المنطقة',
    documentCountry: 'البلاد',
    documentCity: 'المدينة',
    documentTown: 'المدينة',
    documentVillage: 'القرية',
    documentStreet: 'الشارع',
    documentRoad: 'الطريق',
    documentAvenue: 'الشارع',
    documentBoulevard: 'الشارع',
    documentLane: 'الممر',
    documentPath: 'المسار',
    documentWay: 'الطريق',
    documentRoute: 'المسار',
    documentDirection: 'الاتجاه',
    documentDistance: 'المسافة',
    documentLength: 'الطول',
    documentWidth: 'العرض',
    documentHeight: 'الارتفاع',
    documentDepth: 'العمق',
    documentSize: 'الحجم',
    documentWeight: 'الوزن',
    documentMass: 'الكتلة',
    documentVolume: 'الحجم',
    documentCapacity: 'السعة',
    documentSpeed: 'السرعة',
    documentVelocity: 'السرعة',
    documentAcceleration: 'التسارع',
    documentForce: 'القوة',
    documentPressure: 'الضغط',
    documentTemperature: 'درجة الحرارة',
    documentHeat: 'الحرارة',
    documentCold: 'البرودة',
    documentWarm: 'الدفء',
    documentCool: 'البرودة',
    documentHot: 'السخونة',
    documentFreezing: 'التجميد',
    documentBoiling: 'الغليان',
    documentMelting: 'الذوبان',
    documentSolid: 'الصلابة',
    documentLiquid: 'السائل',
    documentGas: 'الغاز',
    documentPlasma: 'البلازما',
    documentMatter: 'المادة',
    documentEnergy: 'الطاقة',
    documentPower: 'القوة',
    documentStrength: 'القوة',
    documentWeakness: 'الضعف',
    documentStrong: 'قوي',
    documentWeak: 'ضعيف',
    documentHard: 'قاس',
    documentSoft: 'ناعم',
    documentSmooth: 'ناعم',
    documentRough: 'خشن',
    documentSharp: 'حاد',
    documentDull: 'بليد',
    documentBright: 'مشرق',
    documentDark: 'مظلم',
    documentLight: 'فاتح',
    documentHeavy: 'ثقيل',
    documentLight: 'خفيف',
    documentBig: 'كبير',
    documentSmall: 'صغير',
    documentLarge: 'كبير',
    documentTiny: 'صغير جداً',
    documentHuge: 'ضخم',
    documentEnormous: 'هائل',
    documentGiant: 'عملاق',
    documentMiniature: 'مصغر',
    documentMicro: 'دقيق',
    documentMacro: 'كبير',
    documentMega: 'كبير جداً',
    documentGiga: 'كبير جداً',
    documentTera: 'كبير جداً',
    documentPeta: 'كبير جداً',
    documentExa: 'كبير جداً',
    documentZetta: 'كبير جداً',
    documentYotta: 'كبير جداً',
    documentKilo: 'كيلو',
    documentHecto: 'هكتو',
    documentDeca: 'ديكا',
    documentDeci: 'ديسي',
    documentCenti: 'ستي',
    documentMilli: 'ملي',
    documentMicro: 'ميكرو',
    documentNano: 'نانو',
    documentPico: 'بيكو',
    documentFemto: 'فمتو',
    documentAtto: 'أتو',
    documentZepto: 'زبتو',
    documentYocto: 'يوكتو',
    
    // Waiting List specific translations
    waitingListTitle: 'قائمة الانتظار',
    waitingListSubtitle: 'إدارة المنتجات في قائمة الانتظار',
    waitingListEmpty: 'قائمة الانتظار فارغة',
    waitingListEmptyDescription: 'لا توجد منتجات في قائمة الانتظار حالياً',
    waitingListAddProduct: 'إضافة منتج',
    waitingListRemoveProduct: 'إزالة منتج',
    waitingListClearAll: 'مسح الكل',
    waitingListConfirmClear: 'هل أنت متأكد من مسح جميع المنتجات من قائمة الانتظار؟',
    waitingListProductName: 'اسم المنتج',
    waitingListProductCode: 'كود المنتج',
    waitingListProductDescription: 'وصف المنتج',
    waitingListProductCategory: 'فئة المنتج',
    waitingListProductSize: 'حجم المنتج',
    waitingListProductLocation: 'موقع المنتج',
    waitingListProductImage: 'صورة المنتج',
    waitingListProductQuantity: 'الكمية',
    waitingListProductUnit: 'الوحدة',
    waitingListProductUnitPrice: 'سعر الوحدة',
    waitingListProductTotalPrice: 'السعر الإجمالي',
    waitingListProductNotes: 'ملاحظات المنتج',
    waitingListProductStatus: 'حالة المنتج',
    waitingListProductCreatedAt: 'تاريخ الإنشاء',
    waitingListProductUpdatedAt: 'تاريخ التحديث',
    waitingListProductActions: 'الإجراءات',
    waitingListProductEdit: 'تعديل المنتج',
    waitingListProductDelete: 'حذف المنتج',
    waitingListProductView: 'عرض المنتج',
    waitingListProductDuplicate: 'نسخ المنتج',
    waitingListProductArchive: 'أرشفة المنتج',
    waitingListProductRestore: 'استعادة المنتج',
    waitingListProductActivate: 'تفعيل المنتج',
    waitingListProductDeactivate: 'إلغاء تفعيل المنتج',
    waitingListProductEnable: 'تمكين المنتج',
    waitingListProductDisable: 'تعطيل المنتج',
    waitingListProductShow: 'إظهار المنتج',
    waitingListProductHide: 'إخفاء المنتج',
    waitingListProductLock: 'قفل المنتج',
    waitingListProductUnlock: 'فتح المنتج',
    waitingListProductSecure: 'تأمين المنتج',
    waitingListProductUnsecure: 'إلغاء تأمين المنتج',
    waitingListProductProtect: 'حماية المنتج',
    waitingListProductUnprotect: 'إلغاء حماية المنتج',
    waitingListProductPrivate: 'جعل المنتج خاص',
    waitingListProductPublic: 'جعل المنتج عام',
    waitingListProductInternal: 'جعل المنتج داخلي',
    waitingListProductExternal: 'جعل المنتج خارجي',
    waitingListProductLocal: 'جعل المنتج محلي',
    waitingListProductRemote: 'جعل المنتج بعيد',
    waitingListProductOnline: 'جعل المنتج متصل',
    waitingListProductOffline: 'جعل المنتج غير متصل',
    waitingListProductAvailable: 'جعل المنتج متاح',
    waitingListProductUnavailable: 'جعل المنتج غير متاح',
    waitingListProductAccessible: 'جعل المنتج يمكن الوصول إليه',
    waitingListProductInaccessible: 'جعل المنتج لا يمكن الوصول إليه',
    waitingListProductVisible: 'جعل المنتج مرئي',
    waitingListProductInvisible: 'جعل المنتج غير مرئي',
    waitingListProductHidden: 'جعل المنتج مخفي',
    waitingListProductShown: 'جعل المنتج مُظهر',
    waitingListProductDisplayed: 'جعل المنتج معروض',
    waitingListProductOpen: 'فتح المنتج',
    waitingListProductClose: 'إغلاق المنتج',
    waitingListProductActive: 'تفعيل المنتج',
    waitingListProductInactive: 'إلغاء تفعيل المنتج',
    waitingListProductEnabled: 'تمكين المنتج',
    waitingListProductDisabled: 'تعطيل المنتج',
    waitingListProductOn: 'تشغيل المنتج',
    waitingListProductOff: 'إيقاف المنتج',
    waitingListProductUp: 'رفع المنتج',
    waitingListProductDown: 'خفض المنتج',
    waitingListProductLeft: 'تحريك المنتج لليسار',
    waitingListProductRight: 'تحريك المنتج لليمين',
    waitingListProductTop: 'تحريك المنتج للأعلى',
    waitingListProductBottom: 'تحريك المنتج للأسفل',
    waitingListProductFront: 'تحريك المنتج للأمام',
    waitingListProductBack: 'تحريك المنتج للخلف',
    waitingListProductInside: 'تحريك المنتج للداخل',
    waitingListProductOutside: 'تحريك المنتج للخارج',
    waitingListProductHere: 'تحريك المنتج هنا',
    waitingListProductThere: 'تحريك المنتج هناك',
    waitingListProductEverywhere: 'تحريك المنتج في كل مكان',
    waitingListProductNowhere: 'تحريك المنتج في أي مكان',
    waitingListProductSomewhere: 'تحريك المنتج في مكان ما',
    waitingListProductAnywhere: 'تحريك المنتج في أي مكان',
    waitingListProductHome: 'تحريك المنتج للمنزل',
    waitingListProductWork: 'تحريك المنتج للعمل',
    waitingListProductSchool: 'تحريك المنتج للمدرسة',
    waitingListProductOffice: 'تحريك المنتج للمكتب',
    waitingListProductStore: 'تحريك المنتج للمتجر',
    waitingListProductShop: 'تحريك المنتج للمحل',
    waitingListProductMarket: 'تحريك المنتج للسوق',
    waitingListProductMall: 'تحريك المنتج للمول',
    waitingListProductCenter: 'تحريك المنتج للمركز',
    waitingListProductPlace: 'تحريك المنتج للمكان',
    waitingListProductLocation: 'تحريك المنتج للموقع',
    waitingListProductPosition: 'تحريك المنتج للموضع',
    waitingListProductSpot: 'تحريك المنتج للنقطة',
    waitingListProductPoint: 'تحريك المنتج للنقطة',
    waitingListProductArea: 'تحريك المنتج للمنطقة',
    waitingListProductZone: 'تحريك المنتج للمنطقة',
    waitingListProductRegion: 'تحريك المنتج للمنطقة',
    waitingListProductCountry: 'تحريك المنتج للبلد',
    waitingListProductCity: 'تحريك المنتج للمدينة',
    waitingListProductTown: 'تحريك المنتج للبلدة',
    waitingListProductVillage: 'تحريك المنتج للقرية',
    waitingListProductStreet: 'تحريك المنتج للشارع',
    waitingListProductRoad: 'تحريك المنتج للطريق',
    waitingListProductAvenue: 'تحريك المنتج للشارع',
    waitingListProductBoulevard: 'تحريك المنتج للشارع',
    waitingListProductLane: 'تحريك المنتج للممر',
    waitingListProductPath: 'تحريك المنتج للمسار',
    waitingListProductWay: 'تحريك المنتج للطريق',
    waitingListProductRoute: 'تحريك المنتج للمسار',
    waitingListProductDirection: 'تحريك المنتج للاتجاه',
    waitingListProductDistance: 'تحريك المنتج للمسافة',
    waitingListProductLength: 'تحريك المنتج للطول',
    waitingListProductWidth: 'تحريك المنتج للعرض',
    waitingListProductHeight: 'تحريك المنتج للارتفاع',
    waitingListProductDepth: 'تحريك المنتج للعمق',
    waitingListProductSize: 'تحريك المنتج للحجم',
    waitingListProductWeight: 'تحريك المنتج للوزن',
    waitingListProductMass: 'تحريك المنتج للكتلة',
    waitingListProductVolume: 'تحريك المنتج للحجم',
    waitingListProductCapacity: 'تحريك المنتج للسعة',
    waitingListProductSpeed: 'تحريك المنتج للسرعة',
    waitingListProductVelocity: 'تحريك المنتج للسرعة',
    waitingListProductAcceleration: 'تحريك المنتج للتسارع',
    waitingListProductForce: 'تحريك المنتج للقوة',
    waitingListProductPressure: 'تحريك المنتج للضغط',
    waitingListProductTemperature: 'تحريك المنتج لدرجة الحرارة',
    waitingListProductHeat: 'تحريك المنتج للحرارة',
    waitingListProductCold: 'تحريك المنتج للبرودة',
    waitingListProductWarm: 'تحريك المنتج للدفء',
    waitingListProductCool: 'تحريك المنتج للبرودة',
    waitingListProductHot: 'تحريك المنتج للسخونة',
    waitingListProductFreezing: 'تحريك المنتج للتجميد',
    waitingListProductBoiling: 'تحريك المنتج للغليان',
    waitingListProductMelting: 'تحريك المنتج للذوبان',
    waitingListProductSolid: 'تحريك المنتج للصلابة',
    waitingListProductLiquid: 'تحريك المنتج للسائل',
    waitingListProductGas: 'تحريك المنتج للغاز',
    waitingListProductPlasma: 'تحريك المنتج للبلازما',
    waitingListProductMatter: 'تحريك المنتج للمادة',
    waitingListProductEnergy: 'تحريك المنتج للطاقة',
    waitingListProductPower: 'تحريك المنتج للقوة',
    waitingListProductStrength: 'تحريك المنتج للقوة',
    waitingListProductWeakness: 'تحريك المنتج للضعف',
    waitingListProductStrong: 'تحريك المنتج للقوة',
    waitingListProductWeak: 'تحريك المنتج للضعف',
    waitingListProductHard: 'تحريك المنتج للقساوة',
    waitingListProductSoft: 'تحريك المنتج للنعومة',
    waitingListProductSmooth: 'تحريك المنتج للنعومة',
    waitingListProductRough: 'تحريك المنتج للخشونة',
    waitingListProductSharp: 'تحريك المنتج للحدة',
    waitingListProductDull: 'تحريك المنتج للبساطة',
    waitingListProductBright: 'تحريك المنتج للسطوع',
    waitingListProductDark: 'تحريك المنتج للظلام',
    waitingListProductLight: 'تحريك المنتج للضوء',
    waitingListProductHeavy: 'تحريك المنتج للثقل',
    waitingListProductLight: 'تحريك المنتج للخفة',
    waitingListProductBig: 'تحريك المنتج للكبر',
    waitingListProductSmall: 'تحريك المنتج للصغر',
    waitingListProductLarge: 'تحريك المنتج للكبر',
    waitingListProductTiny: 'تحريك المنتج للصغر جداً',
    waitingListProductHuge: 'تحريك المنتج للضخامة',
    waitingListProductEnormous: 'تحريك المنتج للهائلة',
    waitingListProductGiant: 'تحريك المنتج للعملاقة',
    waitingListProductMiniature: 'تحريك المنتج للمصغر',
    waitingListProductMicro: 'تحريك المنتج للدقيق',
    waitingListProductMacro: 'تحريك المنتج للكبير',
    waitingListProductMega: 'تحريك المنتج للكبير جداً',
    waitingListProductGiga: 'تحريك المنتج للكبير جداً',
    waitingListProductTera: 'تحريك المنتج للكبير جداً',
    waitingListProductPeta: 'تحريك المنتج للكبير جداً',
    waitingListProductExa: 'تحريك المنتج للكبير جداً',
    waitingListProductZetta: 'تحريك المنتج للكبير جداً',
    waitingListProductYotta: 'تحريك المنتج للكبير جداً',
    waitingListProductKilo: 'تحريك المنتج للكيلو',
    waitingListProductHecto: 'تحريك المنتج للهكتو',
    waitingListProductDeca: 'تحريك المنتج للديكا',
    waitingListProductDeci: 'تحريك المنتج للديسي',
    waitingListProductCenti: 'تحريك المنتج للستي',
    waitingListProductMilli: 'تحريك المنتج للملي',
    waitingListProductMicro: 'تحريك المنتج للميكرو',
    waitingListProductNano: 'تحريك المنتج للنانو',
    waitingListProductPico: 'تحريك المنتج للبيكو',
    waitingListProductFemto: 'تحريك المنتج للفمتو',
    waitingListProductAtto: 'تحريك المنتج للأتو',
    waitingListProductZepto: 'تحريك المنتج للزبتو',
    waitingListProductYocto: 'تحريك المنتج لليوكتو'
  },
  fr: {
    // Navigation
    dashboard: 'Tableau de bord',
    pos: 'Point de vente',
    inventory: 'Inventaire',
    suppliers: 'Fournisseurs',
    clients: 'Clients',
    documents: 'Documents',
    waitingList: 'Liste d\'attente',
    reports: 'Rapports',
    settings: 'Paramètres',
    
    // Common
    search: 'Rechercher',
    add: 'Ajouter',
    edit: 'Modifier',
    delete: 'Supprimer',
    save: 'Enregistrer',
    cancel: 'Annuler',
    confirm: 'Confirmer',
    name: 'Nom',
    phone: 'Téléphone',
    address: 'Adresse',
    email: 'E-mail',
    price: 'Prix',
    quantity: 'Quantité',
    total: 'Total',
    date: 'Date',
    status: 'Statut',
    actions: 'Actions',
    
    // POS
    cart: 'Panier',
    checkout: 'Paiement',
    cash: 'Espèces',
    card: 'Carte',
    credit: 'Crédit',
    partial: 'Paiement partiel',
    
    // Products
    product: 'Produit',
    products: 'Produits',
    buyPrice: 'Prix d\'achat',
    sellPrice: 'Prix de vente',
    stock: 'Stock',
    expiryDate: 'Date d\'expiration',
    lowStock: 'Stock faible',
    
    // Dashboard
    todaySales: 'Ventes du jour',
    totalProducts: 'Total produits',
    totalSuppliers: 'Total fournisseurs',
    totalClients: 'Total clients',
    recentSales: 'Ventes récentes',
    stockAlerts: 'Alertes de stock',
    
    // Company
    companyName: 'BRIQUIN',
    
    // Workflow
    workflow: 'Flux de travail',
    purchaseOrder: 'Bon de commande fournisseur',
    goodsReception: 'Réception des marchandises',
    stockIn: 'Entrée en stock',
    salesOrder: 'Bon de commande client',
    deliveryNote: 'Bon de livraison',
    invoice: 'Facture',
    
    // Workflow Status
    pending: 'En attente',
    inProgress: 'En cours',
    completed: 'Terminé',
    cancelled: 'Annulé',
    
    // Document Types
    supplierPurchaseOrder: 'Bon de commande fournisseur',
    receptionSlip: 'Bon de réception',
    stockEntry: 'Entrée de stock',
    customerSalesOrder: 'Bon de commande client',
    deliverySlip: 'Bon de livraison',
    invoiceDoc: 'Facture',
    
    // Additional Terms
    traceability: 'Traçabilité',
    documentNumber: 'Numéro de document',
    workflowStatus: 'Statut du flux',
    linkedDocuments: 'Documents liés',
    createDocument: 'Créer un document',
    viewWorkflow: 'Voir le flux',
    trackOrder: 'Suivre la commande',
    
    // Settings
    generalSettings: 'Paramètres généraux',
    companyInfo: 'Informations entreprise',
    userManagement: 'Gestion des utilisateurs',
    systemPreferences: 'Préférences système',
    backupRestore: 'Sauvegarde et restauration',
    notifications: 'Notifications',
    security: 'Sécurité',
    integrations: 'Intégrations',
    
    // Company Information
    companyAddress: 'Adresse de l\'entreprise',
    companyPhone: 'Téléphone de l\'entreprise',
    companyEmail: 'Email de l\'entreprise',
    taxNumber: 'Numéro fiscal',
    commercialRegister: 'Registre de commerce',
    
    // User Management
    users: 'Utilisateurs',
    roles: 'Rôles',
    permissions: 'Permissions',
    addUser: 'Ajouter utilisateur',
    editUser: 'Modifier utilisateur',
    deleteUser: 'Supprimer utilisateur',
    username: 'Nom d\'utilisateur',
    password: 'Mot de passe',
    role: 'Rôle',
    lastLogin: 'Dernière connexion',
    
    // System Preferences
    language: 'Langue',
    theme: 'Thème',
    currency: 'Devise',
    dateFormat: 'Format de date',
    timeZone: 'Fuseau horaire',
    
    // Notifications
    emailNotifications: 'Notifications email',
    smsNotifications: 'Notifications SMS',
    systemAlerts: 'Alertes système',
    lowStockAlerts: 'Alertes stock bas',
    expirationAlerts: 'Alertes d\'expiration',
    
    // Additional missing translations
    category: 'Catégorie',
    expiration: 'Expiration',
    expiringSoon: 'Expire bientôt',
    addProduct: 'Ajouter un produit',
    noProductsAdded: 'Aucun produit ajouté. Cliquez sur "Ajouter un produit" pour commencer.',
    supplierPurchaseOrder: 'Bon de commande fournisseur',
    receptionSlip: 'Bon de réception',
    stockEntry: 'Entrée en stock',
    customerSalesOrder: 'Bon de commande client',
    deliveryNote: 'Bon de livraison',
    invoiceDoc: 'Facture',
    linkedDocuments: 'Documents liés',
    newDocument: 'Nouveau document',
    filters: 'Filtres',
    manageAllDocuments: 'Gérer tous vos documents commerciaux',
    totalDocuments: 'Total Documents',
    paid: 'Payés',
    pending: 'En attente',
    totalAmount: 'Montant Total',
    searchByNumber: 'Rechercher par numéro, client ou fournisseur...',
    allStatuses: 'Tous les statuts',
    allDocuments: 'Tous les documents',
    type: 'Type',
    number: 'Numéro',
    step: 'Étape',
    clientSupplier: 'Client/Fournisseur',
    amount: 'Montant',
    linked: 'liés',
    viewDocument: 'Voir le document',
    downloadPDF: 'Télécharger PDF',
    editDocument: 'Modifier le document',
    deleteDocument: 'Supprimer le document',
    noDocumentsFound: 'Aucun document trouvé',
    loadingDocuments: 'Chargement des documents...',
    errorLoadingDocuments: 'Erreur lors du chargement des documents',
    retry: 'Réessayer',
    
    // Missing translations
    code: 'Code',
    stateQuantity: 'État quantité',
    modifyDocument: 'Modifier le document',
    spectateDocument: 'Observer le document',
    close: 'Fermer',
    
    // Document form fields
    documentType: 'Type de document',
    notModifiable: 'non modifiable',
    selectType: 'Sélectionner un type',
    status: 'Statut',
    documentStatus: 'Statut du document',
    draft: 'Brouillon',
    sent: 'Envoyé',
    paid: 'Payé',
    cancelled: 'Annulé',
    totalAmount: 'Montant total',
    client: 'Client',
    selectClient: 'Sélectionner un client',
    supplier: 'Fournisseur',
    selectSupplier: 'Sélectionner un fournisseur',
    
    // Reports page
    lowStockProducts: 'Produits en rupture de stock',
    stock: 'Stock',
    lowStock: 'Stock bas',
    min: 'Min',
    allStocksCorrect: 'Tous les stocks sont corrects',
    clientsWithHighCredit: 'Clients avec crédit élevé',
    purchases: 'Achats',
    credit: 'Crédit',
    noClientsWithHighCredit: 'Aucun client avec crédit élevé',
    monthlyEvolution: 'Évolution mensuelle',
    
    // Document modification specific fields
    automaticDocument: 'Document automatique',
    documentGeneratedByWorkflow: 'Ce document a été généré automatiquement par le workflow.',
    supplierOrderDetails: 'Détails de la commande fournisseur',
    desiredDeliveryDate: 'Date de livraison souhaitée',
    orderedProducts: 'Produits commandés',
    nameCode: 'Nom/Code',
    select: 'Sélectionner',
    addToWaitingList: 'Ajouter à la liste d\'attente',
    addWithMissingQuantity: 'Ajouter avec quantité manquante',
    addWithSurplusQuantity: 'Ajouter avec quantité surplus',
    
    // Waiting List page translations
    waitingListTitle: 'Liste d\'attente des produits',
    total: 'Total',
    clear: 'Vider',
    noProductsInWaitingList: 'Aucun produit dans la liste d\'attente pour le moment.',
    name: 'Nom',
    category: 'Catégorie',
    missingQuantity: 'Quantité manquante',
    surplusQuantity: 'Quantité surplus',
    unit: 'Unité',
    unitPrice: 'Prix unitaire',
    totalPrice: 'Total',
    quantity: 'Quantité',
    actions: 'Actions',
    normal: 'Normale',
    missing: 'Manquante',
    surplus: 'Surplus',
    addToInventory: 'Ajouter à l\'inventaire',
    addNormalQuantity: 'Ajouter quantité normale',
    remove: 'Supprimer',
    cannotAddToInventoryMissing: 'Ce produit ne peut pas être ajouté à l\'inventaire car il a une quantité manquante. Veuillez d\'abord résoudre le problème de quantité manquante.',
    confirmAddNormalQuantity: 'Ce produit a une quantité surplus de {surplusQuantity}. Voulez-vous ajouter seulement la quantité normale ({quantity}) à l\'inventaire ? La quantité surplus restera dans la liste d\'attente.',
    confirmClearWaitingList: 'Vider toute la liste d\'attente ?',
    
    // Document modification/viewing fields
    documentNumber: 'Numéro',
    documentDate: 'Date',
    documentClient: 'Client',
    documentSupplier: 'Fournisseur',
    documentItems: 'Articles',
    documentTotal: 'Total',
    documentSubtotal: 'Sous-total',
    documentTax: 'Taxe',
    documentDiscount: 'Remise',
    documentShipping: 'Livraison',
    documentPayment: 'Paiement',
    documentNotes: 'Notes',
    documentStatus: 'Statut',
    documentType: 'Type',
    documentAmount: 'Montant',
    documentWorkflow: 'Flux de travail',
    documentLinked: 'Lié',
    documentActions: 'Actions',
    documentEdit: 'Modifier',
    documentDelete: 'Supprimer',
    documentDownload: 'Télécharger',
    documentPrint: 'Imprimer',
    documentEmail: 'Envoyer',
    documentDuplicate: 'Dupliquer',
    documentArchive: 'Archiver',
    documentRestore: 'Restaurer',
    documentClose: 'Fermer',
    documentSave: 'Sauvegarder',
    documentCancel: 'Annuler',
    documentConfirm: 'Confirmer',
    documentBack: 'Retour',
    documentNext: 'Suivant',
    documentPrevious: 'Précédent',
    documentFirst: 'Premier',
    documentLast: 'Dernier',
    documentAll: 'Tous',
    documentNone: 'Aucun',
    documentSome: 'Quelques',
    documentMany: 'Beaucoup',
    documentFew: 'Peu',
    documentOther: 'Autres',
    documentAnother: 'Autre',
    documentSame: 'Même',
    documentDifferent: 'Différent',
    documentSimilar: 'Similaire',
    documentIdentical: 'Identique',
    documentUnique: 'Unique',
    documentCommon: 'Commun',
    documentRare: 'Rare',
    documentFrequent: 'Fréquent',
    documentOccasional: 'Occasionnel',
    documentRegular: 'Régulier',
    documentIrregular: 'Irrégulier',
    documentConstant: 'Constant',
    documentVariable: 'Variable',
    documentFixed: 'Fixe',
    documentFlexible: 'Flexible',
    documentRigid: 'Rigide',
    documentSoft: 'Souple',
    documentHard: 'Dur',
    documentEasy: 'Facile',
    documentDifficult: 'Difficile',
    documentSimple: 'Simple',
    documentComplex: 'Complexe',
    documentBasic: 'Basique',
    documentAdvanced: 'Avancé',
    documentBeginner: 'Débutant',
    documentExpert: 'Expert',
    documentProfessional: 'Professionnel',
    documentAmateur: 'Amateur',
    documentSkilled: 'Qualifié',
    documentUnskilled: 'Non qualifié',
    documentTrained: 'Formé',
    documentUntrained: 'Non formé',
    documentQualified: 'Qualifié',
    documentUnqualified: 'Non qualifié',
    documentCertified: 'Certifié',
    documentUncertified: 'Non certifié',
    documentLicensed: 'Licencié',
    documentUnlicensed: 'Non licencié',
    documentAuthorized: 'Autorisé',
    documentUnauthorized: 'Non autorisé',
    documentPermitted: 'Permis',
    documentProhibited: 'Interdit',
    documentAllowed: 'Autorisé',
    documentForbidden: 'Interdit',
    documentLegal: 'Légal',
    documentIllegal: 'Illégal',
    documentValid: 'Valide',
    documentInvalid: 'Invalide',
    documentCorrect: 'Correct',
    documentIncorrect: 'Incorrect',
    documentRight: 'Juste',
    documentWrong: 'Faux',
    documentTrue: 'Vrai',
    documentFalse: 'Faux',
    documentYes: 'Oui',
    documentNo: 'Non',
    documentOk: 'OK',
    documentCancel: 'Annuler',
    documentConfirm: 'Confirmer',
    documentDeny: 'Refuser',
    documentAllow: 'Permettre',
    documentBlock: 'Bloquer',
    documentUnblock: 'Débloquer',
    documentLock: 'Verrouiller',
    documentUnlock: 'Déverrouiller',
    documentSecure: 'Sécurisé',
    documentInsecure: 'Non sécurisé',
    documentSafe: 'Sûr',
    documentUnsafe: 'Dangereux',
    documentProtected: 'Protégé',
    documentUnprotected: 'Non protégé',
    documentPrivate: 'Privé',
    documentPublic: 'Public',
    documentInternal: 'Interne',
    documentExternal: 'Externe',
    documentLocal: 'Local',
    documentRemote: 'Distant',
    documentOnline: 'En ligne',
    documentOffline: 'Hors ligne',
    documentAvailable: 'Disponible',
    documentUnavailable: 'Indisponible',
    documentAccessible: 'Accessible',
    documentInaccessible: 'Inaccessible',
    documentVisible: 'Visible',
    documentInvisible: 'Invisible',
    documentHidden: 'Caché',
    documentShown: 'Affiché',
    documentDisplayed: 'Affiché',
    documentOpen: 'Ouvert',
    documentClosed: 'Fermé',
    documentActive: 'Actif',
    documentInactive: 'Inactif',
    documentEnabled: 'Activé',
    documentDisabled: 'Désactivé',
    documentOn: 'Allumé',
    documentOff: 'Éteint',
    documentUp: 'Haut',
    documentDown: 'Bas',
    documentLeft: 'Gauche',
    documentRight: 'Droite',
    documentTop: 'Haut',
    documentBottom: 'Bas',
    documentFront: 'Avant',
    documentBack: 'Arrière',
    documentInside: 'Intérieur',
    documentOutside: 'Extérieur',
    documentHere: 'Ici',
    documentThere: 'Là',
    documentEverywhere: 'Partout',
    documentNowhere: 'Nulle part',
    documentSomewhere: 'Quelque part',
    documentAnywhere: 'N\'importe où',
    documentHome: 'Maison',
    documentWork: 'Travail',
    documentSchool: 'École',
    documentOffice: 'Bureau',
    documentStore: 'Magasin',
    documentShop: 'Boutique',
    documentMarket: 'Marché',
    documentMall: 'Centre commercial',
    documentCenter: 'Centre',
    documentPlace: 'Lieu',
    documentLocation: 'Emplacement',
    documentPosition: 'Position',
    documentSpot: 'Endroit',
    documentPoint: 'Point',
    documentArea: 'Zone',
    documentZone: 'Zone',
    documentRegion: 'Région',
    documentCountry: 'Pays',
    documentCity: 'Ville',
    documentTown: 'Ville',
    documentVillage: 'Village',
    documentStreet: 'Rue',
    documentRoad: 'Route',
    documentAvenue: 'Avenue',
    documentBoulevard: 'Boulevard',
    documentLane: 'Allée',
    documentPath: 'Chemin',
    documentWay: 'Voie',
    documentRoute: 'Route',
    documentDirection: 'Direction',
    documentDistance: 'Distance',
    documentLength: 'Longueur',
    documentWidth: 'Largeur',
    documentHeight: 'Hauteur',
    documentDepth: 'Profondeur',
    documentSize: 'Taille',
    documentWeight: 'Poids',
    documentMass: 'Masse',
    documentVolume: 'Volume',
    documentCapacity: 'Capacité',
    documentSpeed: 'Vitesse',
    documentVelocity: 'Vélocité',
    documentAcceleration: 'Accélération',
    documentForce: 'Force',
    documentPressure: 'Pression',
    documentTemperature: 'Température',
    documentHeat: 'Chaleur',
    documentCold: 'Froid',
    documentWarm: 'Chaud',
    documentCool: 'Frais',
    documentHot: 'Brûlant',
    documentFreezing: 'Gelant',
    documentBoiling: 'Bouillant',
    documentMelting: 'Fondant',
    documentSolid: 'Solide',
    documentLiquid: 'Liquide',
    documentGas: 'Gaz',
    documentPlasma: 'Plasma',
    documentMatter: 'Matière',
    documentEnergy: 'Énergie',
    documentPower: 'Puissance',
    documentStrength: 'Force',
    documentWeakness: 'Faiblesse',
    documentStrong: 'Fort',
    documentWeak: 'Faible',
    documentHard: 'Dur',
    documentSoft: 'Mou',
    documentSmooth: 'Lisse',
    documentRough: 'Rugueux',
    documentSharp: 'Tranchant',
    documentDull: 'Terne',
    documentBright: 'Brillant',
    documentDark: 'Sombre',
    documentLight: 'Clair',
    documentHeavy: 'Lourd',
    documentLight: 'Léger',
    documentBig: 'Grand',
    documentSmall: 'Petit',
    documentLarge: 'Large',
    documentTiny: 'Minuscule',
    documentHuge: 'Énorme',
    documentEnormous: 'Énorme',
    documentGiant: 'Géant',
    documentMiniature: 'Miniature',
    documentMicro: 'Micro',
    documentMacro: 'Macro',
    documentMega: 'Méga',
    documentGiga: 'Giga',
    documentTera: 'Téra',
    documentPeta: 'Péta',
    documentExa: 'Exa',
    documentZetta: 'Zetta',
    documentYotta: 'Yotta',
    documentKilo: 'Kilo',
    documentHecto: 'Hecto',
    documentDeca: 'Déca',
    documentDeci: 'Déci',
    documentCenti: 'Centi',
    documentMilli: 'Milli',
    documentMicro: 'Micro',
    documentNano: 'Nano',
    documentPico: 'Pico',
    documentFemto: 'Femto',
    documentAtto: 'Atto',
    documentZepto: 'Zepto',
    documentYocto: 'Yocto'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      <div dir={isRTL ? 'rtl' : 'ltr'} className={isRTL ? 'font-arabic' : ''}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};